### ISSUE TITLE
[macosx] Ch04 crashes without adding the VK_LAYER_LUNARG_standard_validation layer

### ISSUE THREAD

**Issue by ioannisNoukakis** [Naitsirc98/Vulkan-Tutorial-Java#6]
Hi,

First of all, thank you for porting this tutorial to Java :) very kind of you!

So the setup was a bit messy for me cause I had to add several JVM arguments to get it working:

- `-XstartOnFirstThread`
- `-Dorg.lwjgl.vulkan.libname=/usr/local/lib/libvulkan.dylib`

And it would crash with a SIGSEGV upon calling `vkCreateDevice`.

I made sure to follow the standard installation of the Vulkan SDK.

Somehow after reading a random post on [reddit](https://www.reddit.com/r/vulkan/comments/4o2uej/access_violation_error_on_vkcreatedevice_with_amd/) I've added this validation layer: `VK_LAYER_LUNARG_standard_validation` hoping I would get more debug information out of it and surprisingly it wasn't crashing anymore and I didn't need to specify `-Dorg.lwjgl.vulkan.libname=` anymore.

Is this something I should report here or is it LWJGL related?

**Comment by Naitsirc98** [comment]
Hi!

It probably has to do with MacOS and how LWJGL deals with it. I mainly work on Windows so I can't help you much there, but I'll try.

First of all, make sure you have correctly set up your IDE, environment variables, correct version of Vulkan SDK, JDK, GPU drivers and LWJGL dependencies via Maven, Gradle or whatever package manager you are using.

Probably the error is still there, but the validation layer is preventing your program from crashing... That could happen for example if there is some struct with undefined values, dangling pointers, incorrect enum values, etc. Maybe the validation layer is silently treating that problem.
Did you just run the code as it is or did you rewrite/modify it? The code in this repository is practically equal to the [original tutorial](https://github.com/Overv/VulkanTutorial/blob/master/code/04_logical_device.cpp), so it shouldn't have errors.

As a note, if you read the [documentation](https://vulkan.lunarg.com/doc/view/1.1.114.0/windows/validation_layers.html), it says that `VK_LAYER_LUNARG_standard_validation` layer is no longer recommended, and that you should use `VK_LAYER_KHRONOS_validation` instead.

Try to reproduce this issue in C++, so that we can know if the problem is Vulkan or Java/LWJGL related.

**Comment by ioannisNoukakis** [comment]
Hello, Sorry for the delay :/

I was able to make it work using the C++ setup of the tutorial and the unchanged code.

So basically I was rewriting the code in Scala as I went though this tutorial when I had this issue.

So next I've cloned this repo and tried to run the Chapter 4 class and basically got the same issue:

```
Exception in thread "main" java.lang.RuntimeException: Validation requested but not supported
	at javavulkantutorial.Ch04LogicalDevice$HelloTriangleApplication.createInstance(Ch04LogicalDevice.java:150)
	at javavulkantutorial.Ch04LogicalDevice$HelloTriangleApplication.initVulkan(Ch04LogicalDevice.java:118)
	at javavulkantutorial.Ch04LogicalDevice$HelloTriangleApplication.run(Ch04LogicalDevice.java:94)
	at javavulkantutorial.Ch04LogicalDevice.main(Ch04LogicalDevice.java:388)
```

So I would suspect this is something at LWJGL level.

Also, another surprise was in chapter 06 when I've tried to use the `vkEnumerateDeviceExtensionProperties` method. The resulting isn't a set of String but a `VkExtensionProperties` that has a method `extensionNameString` which returns an empty String instead of the name of the extension. So I guess I took a version of Vulkan that is too recent?

My Vulkan version is 1.2.162
OS: MacOs BigSur 11.1
Java: 1.8.0_242

**Comment by toongeorges** [comment]
You could try to debug the Java code to see what validation layers are supported on the Java side.

Did you enable the EXTDebugUtils.VK_EXT_DEBUG_UTILS_EXTENSION_NAME extensions?  I think without them, the validation layers would not work.

**Comment by toongeorges** [comment]
> Hey so I got it working using only C++ so I guess this is the way to go. Maybe in the future, it will be fixed. Closing this as the issue isn't related to the java tutorial but rather to LWGJL. Thanks for the replies and the help :)

I have the Java tutorial working under Debian and Linux is free to install as a dual boot option.  (I am actually using a MacBook pro that I got as part of a work assignment, but I installed Debian on it, I never developed under macOS).
